replicaCount: 2

image:
  repository: anuja/user-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  className: nginx
  host: user.example.com

config:
  APP_ENV: production

secret:
  DB_PASSWORD: mypassword